#!/bin/bash

# get packagename from changelog
PKGNAME=$(dpkg-parsechangelog  -l ../debian/changelog  -SSource)

POT=po/${PKGNAME}.pot

[ -f $POT ] && mv $POT $POT~
touch $POT

cd .. 
meson setup mesonbuild
cd mesonbuild || exit 
TARGET=${PKGNAME}-pot
meson compile ${TARGET}

cd ../translations

sed -i 's/charset=CHARSET/charset=UTF-8/' ${POT}

if [ -f $POT~ ]; then
    POT_CHANGE=$(diff $POT $POT~ | grep -vE '^([0-9]|-)|POT-Creation-Date:' | wc -l)
    if (( POT_CHANGE == 0 )); then
       echo "No change in POT-file: $POT"
       echo "Keeping existing POT-file"
       mv $POT~ $POT
    else
       echo "New POT-file generated:  $POT"
       echo "Old POT-file: $POT~"
    fi
fi

exit
