#!/bin/bash

#  fehlix test project do not use
#: ${ORGANIZATION:=fehlix}
#: ${PROJECT:=testproject-do-not-use}

PODIR=po

# set transifex organization and project name - if not set in environment already
: ${ORGANIZATION:=anticapitalista}
: ${PROJECT:=antix-development}

# get package name from changelog
CHNGLOG=$(find {,../,../../}debian/changelog  -type f -name changelog -print -quit 2>/dev/null)
PKGNAME=$(dpkg-parsechangelog -l "$CHNGLOG" -SSource)
# set transifex resource name here if it is not the package name
RESOURCE=$PKGNAME

# set minium translations completion in percent to pull translation
: ${MINIMUM_PERC:=10}

echodo() { echo "${@}";  ${@}; }

# need 'latest' transifex client
: ${TXBIN:=$(which tx)}
[ ! -x "$TXBIN" ] && echo "Error: transifex client not found!" && exit 1

# prepare transifex 
[ -d .tx         ] || mkdir -p .tx
[ -f  .tx/config ] && rm  .tx/config

#host = https://www.transifex.com
cat <<EOF > .tx/config
[main]
host = https://app.transifex.com

[o:${ORGANIZATION}:p:${PROJECT}:r:${RESOURCE}]

file_filter = ${PODIR}/<lang>.po
minimum_perc = ${MINIMUM_PERC:=5}
resource_name = ${RESOURCE}
source_file = ${PODIR}/$PKGNAME.pot
source_lang = en
type = PO
EOF

# remove existing - if any yet
[ -d ${PODIR} ] && echodo rm ${PODIR}/*.po 2>/dev/null
[ -d ${PODIR} ] || echodo mkdir ${PODIR}

# set transifex resource_id
RESOUCE_ID="${PROJECT}.${RESOURCE}"

#echodo ${TXBIN} pull --force  --all "$RESOUCE_ID"
echodo  ${TXBIN} pull --translations --all "$RESOUCE_ID"

# make LINGUAS
LINGUAS=${PODIR}/LINGUAS
[ -f $LINGUAS ] && echodo rm $LINGUAS
touch $LINGUAS

cat<<LINGUAS | tee $LINGUAS
# LINGUAS with minimum completion percent ${MINIMUM_PERC}% 
# generated at $(LANG=C.UTF-8 TZ=EST date -R)
#
LINGUAS

for po in ${PODIR}/*.po; do
    [ -e "$po" ] || continue
    lang=${po##*/}
    lang=${lang%.po}
    printf '%s ' "${lang}"
    echo "${lang}" >> $LINGUAS
done

